stages:
    - deploy_build
    - deploy_up_dev
    - deploy_up_rel

deploy_build:
  image: node:12
  stage: deploy_build
  script:
    - yarn install
    - yarn build
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    refs:
      - master
      - development

deploy_up_dev:
  image: docker/compose
  stage: deploy_up_dev
  script:
    - cp -rf docker/developement/* ./
    - docker-compose down --remove-orphans
    - docker-compose up -d --build
  dependencies:
      - deploy_build
  only:
    refs:
      - development

deploy_up_rel:
  image: docker/compose
  stage: deploy_up_rel
  script:
    - cp -rf docker/release/* ./
    - docker-compose down --remove-orphans
    - docker-compose up -d --build
  dependencies:
      - deploy_build
  only:
    refs:
      - master
